### PR TITLE
cherry pick from develop: docker image nginx unprivileged

### PR DESCRIPTION
**Pull request by edevosc2c**
This commit is cherry-pick from develop in order to get this new Docker image into mviewer/mviewer:stable

Thank you

### CODE REVIEW

**Comment by Gaetanbrl** [comment]
@edevosc2c thanks for this PR and contributing to mviewer.

Has this PR been tested with mviewerstudio ?

**Comment by edevosc2c** [comment]
I got the confirmation from Vincent (Geo2France) that it works great:
image

So good for merging!

**Comment by Gaetanbrl** [comment]
Thanks @edevosc2c

**Comment by Gaetanbrl** [comment]
Please @edevosc2c, target develop branch not master. A release will be made tomorrow, I'd like to include this contribution.
Thanks.

**Comment by edevosc2c** [comment]
Sorry I did not found how you manage your branches on the project. It is actually already in the develop branch: https://github.com/mviewer/mviewer/commit/4c453a1e02e0e214c39aee4749955be4c07f2eab

I thought I needed to push it to master branch for promoting it as a stable release. Well if it's already in the develop branch and ready for the release then please close my PR.

**Pull request closed without merging**
